apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: mongodb
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nObrr/bigdata-on-k8s'
    path: repository/helm-charts/mongodb
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-development.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
