apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: kafka-connectors
  # deployed yaml
  namespace: ingestion
spec:
  project: default
  source:
    repoURL: 'https://github.com/nObrr/bigdata-on-k8s'
    path: repository/yamls/ingestion/connectors/
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
