apiVersion: v1
kind: Service
metadata:
  name: svc-lb-kubecost
  namespace: cost
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: cost-analyzer
    app.kubernetes.io/instance: kubecost
