apiVersion: v1
kind: Service
metadata:
  name: svc-lb-superset
  namespace: viz
spec:
  type: LoadBalancer
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    app: superset
    release: superset
