apiVersion: v1
kind: Service
metadata:
  name: svc-lb-kafka-connect
  namespace: ingestion
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app.kubernetes.io/name: kafka-connect
