apiVersion: v1
kind: Service
metadata:
  name: svc-lb-elasticsearch
  namespace: logging
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch-master
